Improve the example descriptions that are seen on the FHIR Artefacts page
hl7au/au-fhir-erequesting pull request #103
Opened 2024-12-15 00:13 UTC by dbojicic

2025-03-12 05:07 UTC, JayMurdoch commented on input/examples/encounter-consultation.xml
> +        <valueMarkdown value="Shows an example for the *AU Core Encounter* profile, representing a general practice consultation. Patient: Fred Roberts."/>
Suggest "Shows an example of an encounter for the *AU Core Encounter* profile, representing a general practice consultation."

2025-03-12 05:08 UTC, JayMurdoch commented on input/examples/order-xray-1.xml
> +    <valueMarkdown value="Shows an example of a request for a Chest X-Ray for the *AU eRequesting Imaging Request* profile. Patient: Fred Roberts."/>
Suggest changing 'Chest X-Ray' to 'chest X-ray' - though @mjosborne1 will take your advice on the common representation.

2025-03-12 05:08 UTC, JayMurdoch commented on input/examples/organization-elimbah-medical-center.xml
> +        <valueMarkdown value="Shows an example of an organisation, Elimbah Medical Center, for the *AU Core Organization* profile, with an HPI-O identifier and contact details."/>
Change an to a: "... **a** HPI-O identifier.."

2025-03-12 05:09 UTC, JayMurdoch commented on input/examples/organization-mount-charlton-radiology.xml
> +        <valueMarkdown value="Shows an example of an organisation, Mount Charlton Radiology, for the *AU Core Organization* profile, with an HPI-O, type as a radiology laboratory, contact information
Remove 'an' from "... with an HPI-O, type...."

2025-03-12 05:10 UTC, JayMurdoch commented on input/examples/practitioner-aimee-herbert.xml
> +        <valueMarkdown value="Shows an example of a practitioner, Aimee Herbert, for the *AU Core Practitioner* profile, including the HPI-I and name information."/>
Remove 'the' from "... including **the** HPI-I and name information."

2025-03-12 05:11 UTC, JayMurdoch commented on input/examples/practitioner-guthridge-jarred.xml
> +        <valueMarkdown value="Shows an example of practitioner who has an HPI-I for the *AU Core Practitioner* profile, , including the HPI-I and name information."/>
Change an to a: "Shows an example of a practitioner who has **a** HPI-I..."

2025-03-12 05:12 UTC, JayMurdoch commented on input/examples/practitionerrole-aimee-herbert-pathologist.xml
> +        <valueMarkdown value="Shows an example of a Pathologist role for the *AU Core PractitionerRole* profile, including her Medicare Provider Number, role, telecom and references to the associated
Remove 'her' from "... including **her** Medicare Provider Number..."

2025-03-12 05:18 UTC, JayMurdoch commented on input/examples/practitionerrole-kimberlee-mclaughlin-radiologist.xml
> +        <valueMarkdown value="Shows an example of a Radiologist role for the *AU Core PractitionerRole* profile, including her Medicare Provider Number, role, telecom and references to the associated
Remove 'her' from "... including **her** Medicare Provider Number..."

2025-03-12 05:19 UTC, JayMurdoch requested changes
@mjosborne1 please see review comments. Could you address on behalf of Dusi?

2025-03-12 05:42 UTC, mjosborne1 commented on input/examples/organization-elimbah-medical-center.xml
> +        <valueMarkdown value="Shows an example of an organisation, Elimbah Medical Center, for the *AU Core Organization* profile, with an HPI-O identifier and contact details."/>
I'm going to leave this as is.
"HPI-O" starts with a vowel sound (the letter "H" is pronounced "aitch"), so "an" is used instead of "a."

2025-03-12 05:44 UTC, mjosborne1 commented on input/examples/organization-mount-charlton-radiology.xml
> +        <valueMarkdown value="Shows an example of an organisation, Mount Charlton Radiology, for the *AU Core Organization* profile, with an HPI-O, type as a radiology laboratory, contact information
Same comment as Elimbah MC "an" is OK.

2025-03-12 05:48 UTC, mjosborne1 commented on input/examples/organization-mount-charlton-radiology.xml
> +        <valueMarkdown value="Shows an example of an organisation, Mount Charlton Radiology, for the *AU Core Organization* profile, with an HPI-O, type as a radiology laboratory, contact information
Actually looking at this "radiology laboratory" is a copy paste error, should be "radiology practice"

2025-03-12 05:49 UTC, mjosborne1 commented on input/examples/practitioner-aimee-herbert.xml
> +        <valueMarkdown value="Shows an example of a practitioner, Aimee Herbert, for the *AU Core Practitioner* profile, including the HPI-I and name information."/>
changed to "including HPI-I and name information"

2025-03-12 05:50 UTC, mjosborne1 commented on input/examples/organization-mount-charlton-radiology.xml
> +        <valueMarkdown value="Shows an example of an organisation, Mount Charlton Radiology, for the *AU Core Organization* profile, with an HPI-O, type as a radiology laboratory, contact information
removed "an" from "an HPI-O"

2025-03-12 05:52 UTC, mjosborne1 commented on input/examples/practitioner-guthridge-jarred.xml
> +        <valueMarkdown value="Shows an example of practitioner who has an HPI-I for the *AU Core Practitioner* profile, , including the HPI-I and name information."/>
updated (except for changing `an` to `a`)

2025-03-12 05:52 UTC, mjosborne1 commented on input/examples/practitionerrole-aimee-herbert-pathologist.xml
> +        <valueMarkdown value="Shows an example of a Pathologist role for the *AU Core PractitionerRole* profile, including her Medicare Provider Number, role, telecom and references to the associated
changed as requested

2025-03-12 05:53 UTC, mjosborne1 commented on input/examples/practitionerrole-kimberlee-mclaughlin-radiologist.xml
> +        <valueMarkdown value="Shows an example of a Radiologist role for the *AU Core PractitionerRole* profile, including her Medicare Provider Number, role, telecom and references to the associated
updated

2025-03-12 05:53 UTC, mjosborne1 commented on input/examples/encounter-consultation.xml
> +        <valueMarkdown value="Shows an example for the *AU Core Encounter* profile, representing a general practice consultation. Patient: Fred Roberts."/>
updated

2025-03-12 05:53 UTC, mjosborne1 commented on input/examples/order-xray-1.xml
> +    <valueMarkdown value="Shows an example of a request for a Chest X-Ray for the *AU eRequesting Imaging Request* profile. Patient: Fred Roberts."/>
updated

2025-03-13 02:55 UTC, JayMurdoch commented
Closing PR - all changes and review comments incorporated into #153 due to read only rights for @mjosborne1.

2025-03-13 02:55 UTC, closed without merging