Terminology page changes to add Publisher
hl7au/au-fhir-erequesting pull request #104
Opened 2024-12-15 20:38 UTC by dbojicic

Terminology page changes to add Publisher, to align with the HL7 AU IGs Terminology page changes from ballot [FHIR-47172](https://jira.hl7.org/browse/FHIR-47172) and [FHIR-47175](https://jira.hl7.org/browse/FHIR-47175).

2025-03-12 03:56 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +Terminology supported in AU eRequesting are published in AU Base, the base FHIR specification, [HL7 Terminology (THO)](https://terminology.hl7.org/), or the [National Clinical Terminology Service (NC
Suggest "Terminology supported in AU eRequesting **is**..."

2025-03-12 03:59 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +The following value sets are supported in AU eRequesting, i.e bound as [preferred](https://hl7.org/fhir/R4/terminologies.html#preferred) or stronger to a supported element, element slice, or extensio
Change "AU Core" to "AU eRequesting"

2025-03-12 04:08 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +  <li><strong>ValueSet where used:</strong> The value set(s) that reference the code system.</li>
Update to reflect inclusion of fixed values: "The value set(s) that reference the code system or the profile where a fixed value is applied."

2025-03-12 04:10 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[SNOMED CT (Australian extension)](https://www.healthterminologies.gov.au/access-clinical-terminology/access-fhir-terminology-resources/code-systems/?ui:filter=snomed)|[Gender Identity Response](htt
Add entry for AU eRequesting Pathology Request & AU eRequesting Imaging Request under 'Value set where used' (fixed value on category)

2025-03-12 04:16 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|ValueSet|Profiles and Extensions where used|Available from|
Add value set (and associated code system entry) for [RequestPriority](http://hl7.org/fhir/R4/valueset-request-priority.html) (preferred binding on ServiceRequest.priority)

2025-03-12 04:27 UTC, JayMurdoch requested changes
@mjosborne1 see comments, could you please make changes on behalf of Dusi?
Master merge required to resolve conflicts (this PR is from Dec). Once merged, please take a look at any new entries that may need to have 'Available from' and 'Publisher' populated for code system table.

2025-03-12 22:23 UTC, mjosborne1 commented on input/pagecontent/terminology.md
> +Terminology supported in AU eRequesting are published in AU Base, the base FHIR specification, [HL7 Terminology (THO)](https://terminology.hl7.org/), or the [National Clinical Terminology Service (NC
There are some ValueSets and CodeSystems published in the eRequesting IG also...
Suggest change to:
"Terminology supported in AU eRequesting are published in AU eRequesting, AU Base, ..." or 
"Terminology supported in AU eRequesting are published in this IG, AU Base, ..."

2025-03-12 22:29 UTC, mjosborne1 commented on input/pagecontent/terminology.md
> -This implementation guide does not define any unique code systems. The code systems used in this guide are defined in the base FHIR specification, [AU Base](https://build.fhir.org/ig/hl7au/au-fhir-ba
This is not quite true (TaskTags, CommunicationReason).
 Suggest remove:
"This implementation guide does not define any unique code systems. "
Suggest change to:
"The code systems used in this guide are defined in AU eRequesting, AU Base, ..." or
"The code systems used in this guide are defined in this guide, AU Base, ..."

2025-03-12 22:31 UTC, mjosborne1 requested changes
Please see my inline comments

2025-03-13 01:59 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +Terminology supported in AU eRequesting are published in AU Base, the base FHIR specification, [HL7 Terminology (THO)](https://terminology.hl7.org/), or the [National Clinical Terminology Service (NC
Amended, thanks.

2025-03-13 02:37 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> -This implementation guide does not define any unique code systems. The code systems used in this guide are defined in the base FHIR specification, [AU Base](https://build.fhir.org/ig/hl7au/au-fhir-ba
See amended text below - no reference to this guide not defining unique code systems.

2025-03-21 00:28 UTC, mjosborne1 approved these changes

2025-03-31 03:19 UTC, michael-wilson-au approved these changes

2025-03-31 04:09 UTC, merged