Update eRequesting menus to be like Base and Core
hl7au/au-fhir-erequesting pull request #105
Opened 2024-12-23 21:58 UTC by johnscarter

This PR addresses a [backlog item](https://github.com/orgs/hl7au/projects/10?pane=issue&itemId=87054360) to make the menu changes in [FHIR-47167](https://jira.hl7.org/browse/FHIR-47167) and [FHIR-47172](https://jira.hl7.org/browse/FHIR-47172) in the eRequesting IG.

2024-12-24 02:45 UTC, dbojicic commented on input/pagecontent/fhirartifacts.md
> +
Commenting here to get an inline comment. 

[Guidance](https://build.fhir.org/ig/hl7au/au-fhir-erequesting/branches/ft_update-menus-like-base/guidance.html) page requires a few small changes:
- 'eRequesting Data for Interoperability' should be 'AU eRequesting Data for Interoperability Mappings' to match the page title
- 'Relationship with other IGs' should be 'Relationships to Other Specifications' to match the page title.

2024-12-24 03:02 UTC, dbojicic commented on sushi-config.yaml
>    support.md:
Commenting here to get an inline comment: 
In the Table of Contents: 
1. The entries under 3 Guidance should be reordered to match the order they appear in the main menu, e.g. 3.4 AU eRequesting Data for Interoperability Mappings becomes 3.1 eRequesting Data for Interoperability Mappings
2. The entries under 5 FHIR Artefacts should be reordered to match the order they appear in the main menu, e.g. Terminology comes before Actors and Capabilities. 
Please remove `Search Parameters and Operations`, there is no such page in this IG.
3. Licence under 7 Support should be 'License and Legal'.

2024-12-24 03:04 UTC, dbojicic requested changes
Please see comments.

2025-01-02 18:54 UTC, johnscarter commented on input/pagecontent/fhirartifacts.md
> +
fixed

2025-01-02 19:02 UTC, johnscarter commented on sushi-config.yaml
>    support.md:
done

2025-01-02 22:28 UTC, dbojicic commented on sushi-config.yaml
> +    license.md: License and Legal
Commenting here to get an inline comment. 

1. An additional empty sub-menu item has been introduced now between Downloads and Licence and Legal under Support main menu item. 
2. In the Table of Contents, entry 7.2 License and Legal is missing now.

2025-01-02 22:34 UTC, dbojicic requested changes
Please see comments.

2025-01-02 22:40 UTC, dbojicic commented
@johnscarter, some of the defects currently showing in _1.6 How to read this guide_ in this branch have already been resolved in the master branch. Could you please merge the latest master into your branch to ensure it it is up to date and these issues are addressed? Thank you :)

2025-01-02 22:42 UTC, dbojicic commented on sushi-config.yaml
> +    license.md: License and Legal
Commenting here to get an inline comment.

In the Table of Contents, entry 7.2 License and Legal is now missing, please add.

2025-01-02 22:42 UTC, dbojicic commented on sushi-config.yaml
> +      title: Actors and Capabilities
Commenting here to get an inline comment.

The latest changes caused "The link 'license.html' for "License and Legal" cannot be resolved' errors in the QA Report, please resolve.

2025-01-05 22:20 UTC, johnscarter commented on sushi-config.yaml
> +      title: Actors and Capabilities
done

2025-01-05 23:39 UTC, dbojicic approved these changes

2025-01-05 23:40 UTC, johnscarter commented on sushi-config.yaml
> +    license.md: License and Legal
done

2025-01-05 23:42 UTC, dbojicic approved these changes

2025-01-05 23:49 UTC, merged