Quick fix to add in missing instances for derived profiles
hl7au/au-fhir-erequesting pull request #46
Opened 2024-07-18 06:01 UTC by dt-r

edited terminology page

2024-07-18 11:35 UTC, JayMurdoch commented on input/pagecontent/terminology.md
>  |[Imaging Procedure](https://healthterminologies.gov.au/fhir/ValueSet/imaging-procedure-1)|[AU eRequesting Imaging Request](StructureDefinition-au-erequesting-servicerequest-imag.html)|NCTS|
There are duplicate entries for IdentifierUse value set - please remove.

2024-07-18 12:23 UTC, JayMurdoch requested changes
Review of added content complete with no issues noted.

Suggest the following fixes for page (or advise if new PR should be raised):
* There are duplicate entries for IdentifierUse value set - remove.
* Add Body Site value set, flagged as must support on ServiceRequest.bodySite for Imaging Request and Pathology Request.
* Add ServiceRequestCategoryCodes value set, flagged as must support on ServiceRequest.category for ServiceRequest, Imaging Request and Pathology Request.

2024-07-18 21:12 UTC, dt-r commented
Fixed:

- There are duplicate entries for IdentifierUse value set - remove.
- Add Body Site value set, flagged as must support on ServiceRequest.bodySite for Imaging Request and Pathology Request.
- Add ServiceRequestCategoryCodes value set, flagged as must support on ServiceRequest.category for ServiceRequest, Imaging Request and Pathology Request.

Added in missing entries for value sets & code systems in:
- ContactPoint data type
- Address data type

2024-07-18 23:05 UTC, JayMurdoch requested changes
Additional changes reviewed, no issues.

Two additional minor fixes noted:
* For Australian States and Territories value set profiles where used, change order of profiles to Location/Org/Patient.
* For SNOMED CT code system, change order of value sets to Gender Identity Req/Reason for Req.

2024-07-18 23:19 UTC, dt-r commented
Addressed the comments. If there are any further comments please add them as inline comments on the file.

2024-07-19 01:41 UTC, JayMurdoch approved these changes
Review complete, no issues noted. Thanks.

2024-07-19 01:46 UTC, merged