Add value set binding to task.status
hl7au/au-fhir-erequesting pull request #74
Opened 2024-10-09 04:07 UTC by johnscarter

A final change needed to complete https://jira.hl7.org/browse/FHIR-47081, adding a value set binding to Task.status

2024-10-15 03:23 UTC, dbojicic commented on input/fsh/au-erequesting-task.fsh
> +* status from http://hl7.org.au/fhir/ereq/ValueSet/task-status (required)
Value set URL is incorrect, please see https://build.fhir.org/ig/hl7au/au-fhir-erequesting/branches/master/ValueSet-au-erequesting-task-status.html for details.

2024-10-15 03:23 UTC, dbojicic requested changes
Please see inline comment

2024-10-22 01:28 UTC, dbojicic approved these changes

2024-10-28 22:17 UTC, michael-wilson-au approved these changes

2024-10-29 21:13 UTC, merged