Made AUeReqSvcReq.encounter mandatory FHIR-47008
hl7au/au-fhir-erequesting pull request #77
Opened 2024-10-29 00:30 UTC by johnscarter

Made AU eRequest ServiceRequest . encounter mandatory per [FHIR-47008](https://jira.hl7.org/browse/FHIR-47008).

2024-10-31 07:52 UTC, dbojicic commented on input/pagecontent/changes.md
> +  - Made AUeRequestingServiceRequest.encounter mandatory per [FHIR-47008](https://jira.hl7.org/browse/FHIR-47008)
AUeRequestingServiceRequest.encounter should be ServiceRequest.encounter. 
Please add "(1..1)" after "mandatory" so it reads "mandatory (1..1)"), and remove "per" (sorry to be picky bit we don't use it in change logs in any of the specs).

2024-10-31 07:52 UTC, dbojicic requested changes
Minor changes requested

2024-11-06 01:22 UTC, dbojicic approved these changes

2024-11-07 05:55 UTC, michael-wilson-au approved these changes

2024-11-08 01:55 UTC, merged