FHIR-47119 Conformance Mandatory Elements section rewrite
hl7au/au-fhir-erequesting pull request #91
Opened 2024-11-20 04:00 UTC by johnscarter

Rewrote [Conformance page Mandatory Elements section](https://build.fhir.org/ig/hl7au/au-fhir-erequesting/conformance.html#mandatory-elements) according to [FHIR-47119](https://jira.hl7.org/browse/FHIR-47119).

2024-11-21 10:33 UTC, dbojicic requested changes
Please see comments.

2024-11-28 21:27 UTC, johnscarter commented on input/pagecontent/conformance.md
> -<p class="request-for-feedback">Input is requested on the appropriateness of allowing Missing Data or Suppressed Data for all elements. Please comment by raising <a href="https://jira.hl7.org/project
reinstated

2024-12-03 03:56 UTC, michael-wilson-au commented on input/pagecontent/conformance.md
> -<p class="request-for-feedback">Input is requested on the appropriateness of allowing Missing Data or Suppressed Data for all elements. Please comment by raising <a href="https://jira.hl7.org/project
yes, there was no resolution to remove the request for feedback

2024-12-03 03:56 UTC, michael-wilson-au approved these changes

2024-12-03 07:57 UTC, dbojicic approved these changes

2024-12-03 11:13 UTC, merged